/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.reebow.loga;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.List;

import de.reebow.loga.annotations.LogInput;
import de.reebow.loga.appenders.TestAppender;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.core.LogEvent;
import org.apache.logging.log4j.core.LoggerContext;
import org.apache.logging.log4j.core.config.Configuration;
import org.apache.logging.log4j.spi.StandardLevel;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

class LogInputAspectTest {

  private TestAppender appender;

  @LogInput
  @SuppressWarnings("unused")
  public void methodUnderTest(String name, int age) {

  }

  @BeforeEach
  void setUp() {
    LoggerContext ctx = (LoggerContext) LogManager.getContext(false);
    Configuration config = ctx.getConfiguration();
    appender = (TestAppender) config.getAppenders().get("TestAppender");
  }

  @Test
  @DisplayName("Method with Annotation @LogInput - invoke method - log method name, parameter types, name and value")
  void logInput() {
    methodUnderTest("Daria", 1);

    List<LogEvent> logEvents = appender.getLogEvents();

    assertEquals(1, logEvents.size());
    LogEvent logEvent = logEvents.get(1);

    assertEquals(StandardLevel.DEBUG, logEvent.getLevel().getStandardLevel());
  }

}
