/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.reebow.loga;

import de.reebow.loga.annotations.LogInput;
import org.apache.logging.log4j.spi.StandardLevel;

public class Library {
    @LogInput(StandardLevel.DEBUG)
    public boolean someLibraryMethod(String jojo, int test) {
        return true;
    }
}
